version: '3.4'

services:
  postgres.database:
    image: postgres:16.0
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: default
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  postgres.client:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: jojdzino999@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"

volumes:
  postgres_data: